function subIDs = PTPsubjectIDs(task)
%
% Function that outputs subject IDs of PTP depending on the task
%
% INPUTS
%           task    'aud-reflexive' or 'aud-adaptive'
%
% OUTPUTS
%           subIDs  cell array of relevant subject IDs
%
% Written by Alexander Acosta
% November 3, 2022

if strcmp(task,'aud-reflexive')
    subIDs = {'sub-PTP001',...
        'sub-PTP002',...
        'sub-PTP003',...
        'sub-PTP004',...
        'sub-PTP005',...
        'sub-PTP006',...
        'sub-PTP007',...
        'sub-PTP008',...
        'sub-PTP009',...
        'sub-PTP010',...
        'sub-PTP011',...
        'sub-PTP012',...
        'sub-PTP013',...
        'sub-PTP014',...
        'sub-PTP015',...
        'sub-PTP017',...
        'sub-PTP018',...
        'sub-PTP019',...
        'sub-PTP020',...
        'sub-PTP021',...
        'sub-PTP022',...
        'sub-PTP023',...
        'sub-PTP024'};
elseif strcmp(task,'aud-adaptive')
    subIDs = {'sub-PTP002',...
        'sub-PTP003',...
        'sub-PTP004',...
        'sub-PTP005',...
        'sub-PTP006',...
        'sub-PTP007',...
        'sub-PTP008',...
        'sub-PTP009',...
        'sub-PTP011',...
        'sub-PTP012',...
        'sub-PTP013',...
        'sub-PTP014',...
        'sub-PTP015',...
        'sub-PTP017',...
        'sub-PTP018',...
        'sub-PTP019',...
        'sub-PTP020',...
        'sub-PTP021',...
        'sub-PTP022',...
        'sub-PTP023',...
        'sub-PTP024'};
end