% Matlab session crashed prematurely for PTP001, ses-2, run-4
% Script concatenates completed trial data into experimental mat file

dataDir = '/CONNSERVER/projectnb2/busplab/Experiments/AudDev/sub-PTP001/ses-2/beh/run-4';

trialData = struct('stimName', [],...
    'condLabel', [],...
    'pertJitter', [],...
    'ostFN', [],...
    'pcfFN', [],...
    'audapData', [],...
    'onsetDetected', [],...
    'nonSpeechDelay', [],...
    'rmsVoiceOnset', [],...
    'timingTrial', [],...
    'p', []...
    );

for t = 1:17
    
    FN = conn_cache('pull', fullfile(dataDir, sprintf('sub-PTP001_ses-2_run-4_task-aud-reflexive_trial-%d.mat', t)));
    load(FN, 'tData')
    trialData(t) = tData;
    
end

FN = conn_cache('pull', fullfile(dataDir, 'sub-PTP001_ses-2_run-4_task-aud-reflexive_expParams.mat'));
load(FN,'expParams');
conn_savematfile(fullfile(dataDir, 'sub-PTP001_ses-2_run-4_task-aud-reflexive.mat'), 'expParams', 'trialData')