% graph_pertEpoch(1);  
% graph_pertEpoch(2); 
% graph_pertEpoch(3);  
% graph_pertEpoch(4); 
graph_pertEpoch(5);  
% graph_pertEpoch(6); 
% graph_pertEpoch(7);  
% graph_pertEpoch(8);  
% graph_pertEpoch(9);  
% graph_pertEpoch(10); 
% graph_pertEpoch(11); 
% graph_pertEpoch(12); 
% graph_pertEpoch(13); 
% graph_pertEpoch(16);