% pertEpoch(1,true,true);  
% pertEpoch(2,true,true); 
% pertEpoch(3,true,true);  
% pertEpoch(4,true,true); 
% pertEpoch(5,true,true);  
% pertEpoch(6,true,true); 
% pertEpoch(7,true,true);  
% pertEpoch(8,true,true);  
% pertEpoch(9,true,true);  
% pertEpoch(10,true,true); 
% pertEpoch(11,true,true); 
% pertEpoch(12,true,true); 
% pertEpoch(13,true,true); 
% pertEpoch(15,true,true); 
% pertEpoch(16,true,true);

findAutoExcluded(1);  
findAutoExcluded(2); 
findAutoExcluded(3);  
findAutoExcluded(4); 
findAutoExcluded(5);  
findAutoExcluded(6); 
findAutoExcluded(7);  
findAutoExcluded(8);  
findAutoExcluded(9);  
findAutoExcluded(10); 
findAutoExcluded(11); 
findAutoExcluded(12); 
findAutoExcluded(13); 
findAutoExcluded(15);
findAutoExcluded(16);

%% OLD
% graph_pertEpoch(1);  
% graph_pertEpoch(2); 
% graph_pertEpoch(3);  
% graph_pertEpoch(4); 
% graph_pertEpoch(5);  
% graph_pertEpoch(6); 
% graph_pertEpoch(7);  
% graph_pertEpoch(8);  
% graph_pertEpoch(9);  
% graph_pertEpoch(10); 
% graph_pertEpoch(11); 
% graph_pertEpoch(12); 
% graph_pertEpoch(13); 
% graph_pertEpoch(16);
